### ISSUE TITLE
autosar-xcp-master?

### ISSUE THREAD

**Issue by baoxinqiang** [elupus/autosar-xcp#1]
Does this zip autosar-xcp-master is a "xcp master driver" or a "xcp slave driver". It looks like a xcp-slave driver. Please correct me, If I am wrong, Thanks a lot.

**Comment by elupus** [comment]
It's a slave.

Den tors 21 feb. 2019 11:42baoxinqiang <notifications@github.com> skrev:

**Comment by baoxinqiang** [comment]
Thanks.
